=== marceloodiezz/LaVuelta2026/xml/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.uniovi.es"
    targetNamespace="http://www.uniovi.es"
    elementFormDefault="qualified">

	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="numero" />
				<xs:element ref="longitud" />
				<xs:element ref="fecha" />
				<xs:element ref="tiempoGanador" />
				<xs:element ref="velocidadMedia" />
				<xs:element ref="desnivel" />
				<xs:element ref="salida" />
				<xs:element ref="meta" />
				<xs:element ref="tipo" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotos" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="galeriaSonidos" />
				<xs:element ref="hitos" />
				<xs:element ref="trazado" />
				<xs:element ref="clasificacionEtapa" />
				<xs:element ref="clasificacionGeneral" />
				<xs:element ref="clasificacionEquipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre" type="xs:string" />

	<!-- Tipo simple para poder añadir restricciones al elemento 'numero' -->
	<xs:simpleType name="NumeroEtapaRestriccion">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="21"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="numero" type="NumeroEtapaRestriccion" />
	
	<!-- Tipo simple para poder aplicar restricciones al elemento 'longitud' -->
	<xs:simpleType name="LongitudRestriccion">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LongitudRestriccion">
					<xs:attribute name="unidad" type="xs:string" use="required" fixed="km" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="fecha" type="xs:date" />
	
	<xs:element name="tiempoGanador" type="xs:duration" />

	<!-- Tipo simple para poder aplicar restricciones al elemento 'velocidadMedia' -->
	<xs:simpleType name="VelocidadRestriccion">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="velocidadMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="VelocidadRestriccion">
					<xs:attribute name="unidad" type="xs:string" use="required" fixed="km/h" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:nonNegativeInteger">
					<xs:attribute name="unidad" type="xs:string" use="required" fixed="m" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="salida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lugar" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="meta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lugar" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="lugar" type="xs:string" />
	
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudGeografica" />
				<xs:element ref="latitudGeografica" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Tipo simple para poder aplicar restricciones al elemento 'longitudGeografica' -->
	<xs:simpleType name="LongitudGeograficaRestriccion">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180"/>
			<xs:maxInclusive value="180"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="longitudGeografica">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LongitudGeograficaRestriccion">
					<xs:attribute name="unidad" type="xs:string" use="required" fixed="grados" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!-- Tipo simple para poder aplicar restricciones al elemento 'latitudGeografica' -->
	<xs:simpleType name="LatitudGeograficaRestriccion">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90"/>
			<xs:maxInclusive value="90"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="latitudGeografica">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="LatitudGeograficaRestriccion">
					<xs:attribute name="unidad" type="xs:string" use="required" fixed="grados" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" fixed="m" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!-- Tipo simple para poder aplicar restricciones al elemento 'tipo' -->
	<xs:simpleType name="TipoRestriccion">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Llana"/>
			<xs:enumeration value="Ondulada"/>
			<xs:enumeration value="Media Montaña"/>
			<xs:enumeration value="Montaña"/>
			<xs:enumeration value="Contrarreloj individual"/>
			<xs:enumeration value="Contrarreloj por equipos"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="tipo" type="TipoRestriccion" />
	
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="referencia" minOccurs="3" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="referencia" type="xs:anyURI" />
	
	<xs:element name="galeriaFotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="fotografia" type="xs:anyURI" />
	
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="video" type="xs:anyURI" />
	
	<xs:element name="galeriaSonidos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="sonido" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sonido" type="xs:anyURI" />
	
	<xs:element name="hitos">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="puerto" />
				<xs:element ref="sprint" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="puerto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreHito" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="categoria" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="primera" />
						<xs:enumeration value="segunda" />
						<xs:enumeration value="tercera" />
						<xs:enumeration value="especial" />
						<xs:enumeration value="bonificado" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombreHito" type="xs:string" />

	<!-- Tipo simple para poder aplicar restricciones al elemento 'distancia' -->
	<xs:simpleType name="DistanciaRestriccion">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="DistanciaRestriccion">
					<xs:attribute name="unidad" type="xs:string" use="required" fixed="km" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sprint">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreHito" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="tipo" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="intermedio" />
						<xs:enumeration value="bonificado" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="trazado">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="nombrePunto" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombrePunto" type="xs:string" />
	
	<xs:element name="clasificacionEtapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="clasificado" minOccurs="3" maxOccurs="3"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreCorredor" />
				<xs:element ref="nombreEquipo" />
				<xs:element ref="diferencia" />
			</xs:sequence>
			<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombreCorredor" type="xs:string" />
	
	<xs:element name="nombreEquipo" type="xs:string" />
	
	<xs:element name="diferencia" type="xs:string" />
	
	<xs:element name="clasificacionGeneral">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="clasificado" minOccurs="3" maxOccurs="3"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clasificacionEquipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equipoClasificado" minOccurs="3" maxOccurs="3"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="equipoClasificado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreEquipo" />
				<xs:element ref="diferencia" />
			</xs:sequence>
			<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== marceloodiezz/LaVuelta2026/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<etapa 
    xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es etapa.xsd">

    <nombre>Alcaraz a Elche de la Sierra</nombre>

    <numero>10</numero>
    
    <longitud unidad="km">184.7</longitud>
    
    <fecha>2026-09-01</fecha>
    
    <tiempoGanador>PT4H7M41S</tiempoGanador>
    
    <velocidadMedia unidad="km/h">44.74</velocidadMedia>
    
    <desnivel unidad="m">2991</desnivel>
    
    <salida>
        <lugar>Alcaraz</lugar>
        <coordenadas>
            <longitudGeografica unidad="grados">-2.4926058</longitudGeografica>
            <latitudGeografica unidad="grados">38.6701929</latitudGeografica>
            <altitud unidad="m">839</altitud>
        </coordenadas>
    </salida>

    <meta>
        <lugar>Elche de la Sierra</lugar>
        <coordenadas>
            <longitudGeografica unidad="grados">-2.0495278</longitudGeografica>
            <latitudGeografica unidad="grados">38.4521389</latitudGeografica>
            <altitud unidad="m">644</altitud>
        </coordenadas>
    </meta>
    
    <tipo>Ondulada</tipo>
    
    <referencias>
        <referencia>https://www.lavuelta.es/es/etapa-10</referencia>
        <referencia>https://alcaraz.es/</referencia>
        <referencia>https://elchedelasierra.es/</referencia>
    </referencias>
    
    <galeriaFotos>
        <fotografia>../multimedia/alcaraz.jpg</fotografia>
        <fotografia>../multimedia/elche-de-la-sierra.jpg</fotografia>
    </galeriaFotos>

    <galeriaVideos>
        <video>../multimedia/final-etapa.mp4</video>
    </galeriaVideos>

    <galeriaSonidos>
        <sonido>../multimedia/final-etapa.mp3</sonido>
    </galeriaSonidos>

    <hitos>
        <puerto categoria="tercera">
            <nombreHito>Puerto del Peralejo</nombreHito>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.3059682</longitudGeografica>
                <latitudGeografica unidad="grados">38.4926808</latitudGeografica>
                <altitud unidad="m">1132</altitud>
            </coordenadas>
            <distancia unidad="km">47.6</distancia>
        </puerto>

        <puerto categoria="tercera">
            <nombreHito>Puerto de Aýna</nombreHito>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.0373940</longitudGeografica>
                <latitudGeografica unidad="grados">38.5805260</latitudGeografica>
                <altitud unidad="m">950</altitud>
            </coordenadas>
            <distancia unidad="km">86.3</distancia>
        </puerto>

        <sprint tipo="intermedio">
            <nombreHito>Hellín</nombreHito>
            <coordenadas>
                <longitudGeografica unidad="grados">-1.7020840</longitudGeografica>
                <latitudGeografica unidad="grados">38.5087420</latitudGeografica>
                <altitud unidad="m">546</altitud>
            </coordenadas>
            <distancia unidad="km">125.0</distancia>
        </sprint>

        <sprint tipo="bonificado">
            <nombreHito>Hellín</nombreHito>
            <coordenadas>
                <longitudGeografica unidad="grados">-1.7020840</longitudGeografica>
                <latitudGeografica unidad="grados">38.5087420</latitudGeografica>
                <altitud unidad="m">546</altitud>
            </coordenadas>
            <distancia unidad="km">125.0</distancia>
        </sprint>

        <puerto categoria="tercera">
            <nombreHito>Puerto de Socovos</nombreHito>
            <coordenadas>
                <longitudGeografica unidad="grados">-1.9896330</longitudGeografica>
                <latitudGeografica unidad="grados">38.3380090</latitudGeografica>
                <altitud unidad="m">782</altitud>
            </coordenadas>
            <distancia unidad="km">163.3</distancia>
        </puerto>
    </hitos>

    <trazado>

        <punto>
            <nombrePunto>Alcaraz (Salida)</nombrePunto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.4926058</longitudGeografica>
                <latitudGeografica unidad="grados">38.6701929</latitudGeografica>
                <altitud unidad="m">839</altitud>
            </coordenadas>
            <distancia unidad="km">0</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.5662550</longitudGeografica>
                <latitudGeografica unidad="grados">38.6445256</latitudGeografica>
                <altitud unidad="m">815</altitud>
            </coordenadas>
            <distancia unidad="km">8.0</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.5617965</longitudGeografica>
                <latitudGeografica unidad="grados">38.5997948</latitudGeografica>
                <altitud unidad="m">895</altitud>
            </coordenadas>
            <distancia unidad="km">13.6</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.5023923</longitudGeografica>
                <latitudGeografica unidad="grados">38.5568621</latitudGeografica>
                <altitud unidad="m">1085</altitud>
            </coordenadas>
            <distancia unidad="km">21.8</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.5097056</longitudGeografica>
                <latitudGeografica unidad="grados">38.5152807</latitudGeografica>
                <altitud unidad="m">1251</altitud>
            </coordenadas>
            <distancia unidad="km">27.0</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.3985286</longitudGeografica>
                <latitudGeografica unidad="grados">38.4890987</latitudGeografica>
                <altitud unidad="m">931</altitud>
            </coordenadas>
            <distancia unidad="km">38.3</distancia>
        </punto>

        <punto>
            <nombrePunto>Puerto del Peralejo</nombrePunto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.3059682</longitudGeografica>
                <latitudGeografica unidad="grados">38.4926808</latitudGeografica>
                <altitud unidad="m">1132</altitud>
            </coordenadas>
            <distancia unidad="km">47.6</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.2202702</longitudGeografica>
                <latitudGeografica unidad="grados">38.4835433</latitudGeografica>
                <altitud unidad="m">974</altitud>
            </coordenadas>
            <distancia unidad="km">56.9</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.1865278</longitudGeografica>
                <latitudGeografica unidad="grados">38.5212241</latitudGeografica>
                <altitud unidad="m">1128</altitud>
            </coordenadas>
            <distancia unidad="km">63.4</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.1312977</longitudGeografica>
                <latitudGeografica unidad="grados">38.5216610</latitudGeografica>
                <altitud unidad="m">995</altitud>
            </coordenadas>
            <distancia unidad="km">69.5</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.1043319</longitudGeografica>
                <latitudGeografica unidad="grados">38.5376988</latitudGeografica>
                <altitud unidad="m">977</altitud>
            </coordenadas>
            <distancia unidad="km">73.1</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.1215547</longitudGeografica>
                <latitudGeografica unidad="grados">38.5456351</latitudGeografica>
                <altitud unidad="m">802</altitud>
            </coordenadas>
            <distancia unidad="km">75.2</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.0697780</longitudGeografica>
                <latitudGeografica unidad="grados">38.5534712</latitudGeografica>
                <altitud unidad="m">763</altitud>
            </coordenadas>
            <distancia unidad="km">80.8</distancia>
        </punto>

        <punto>
            <nombrePunto>Puerto de Aýna</nombrePunto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.0373940</longitudGeografica>
                <latitudGeografica unidad="grados">38.5805260</latitudGeografica>
                <altitud unidad="m">950</altitud>
            </coordenadas>
            <distancia unidad="km">86.3</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-2.0268454</longitudGeografica>
                <latitudGeografica unidad="grados">38.5945657</latitudGeografica>
                <altitud unidad="m">909</altitud>
            </coordenadas>
            <distancia unidad="km">88.2</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-1.9455826</longitudGeografica>
                <latitudGeografica unidad="grados">38.5528902</latitudGeografica>
                <altitud unidad="m">757</altitud>
            </coordenadas>
            <distancia unidad="km">97.6</distancia>
        </punto>

        <punto>
            <coordenadas>
                <longitudGeografica unidad="grados">-1.8027205</longitudGeografica>
                <latitudGeografica unidad="grados">38.5269217</latitudGeografica>
